name: ev_charging_station
description: "EV Charging Station Management System Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  mobile_scanner: ^6.0.4
  qr_flutter: ^4.1.0
  fl_chart: ^0.70.2
  percent_indicator: ^4.2.4
  intl: ^0.20.2
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^10.8.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
